name: Tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Init venv
        run: uv venv --python ${{ matrix.python-version }}

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libev-dev

      - name: Install dependencies
        run: |
          uv sync --group dev \
            --extra taskiq \
            --extra msgpack \
            --extra polars \
            --extra excel \
            --extra yaml \
            --extra avro \
            --extra elasticsearch \
            --extra mongodb \
            --extra s3 \
            --extra vortex \
            --extra mysql \
            --extra postgresql \
            --extra gsheets \
            --extra snowflake \
            --extra ftp \
            --extra sftp \
            --extra cassandra \
            --extra couchdb \
            --extra dynamodb \
            --extra winloop
          uv pip install msgpack

      - name: Run tests
        run: uv run --group dev pytest -o "anyio_mode=auto"
